# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/vidharvester', 'vidharvester'),
        ('proxy', 'proxy'),
        ('extensions', 'extensions'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui', 
        'PyQt6.QtWidgets',
        'yt_dlp',
        'requests',
        'beautifulsoup4',
        'mitmproxy',
        'playwright',
        'psutil',
        'sqlite3',
        'vidharvester.app',
        'vidharvester.gui.main_window',
        'vidharvester.capture.extension_server',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
    onefile=True,
)

exe = EXE(
    a.pure,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='VidHarvester-OneFile',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
